table aux_classe_produtos
	lineageTag: 950d36fc-c722-483c-8fd9-e0f0a13de243

	column Segmentação
		dataType: string
		lineageTag: 615aa4ac-2533-4ec4-a980-6ff191b6bff3
		summarizeBy: none
		sourceColumn: Segmentação
		sortByColumn: Id

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: int64
		formatString: 0
		lineageTag: b36a4fc5-ab6a-44ca-a7c7-6c2548ba6ab9
		summarizeBy: count
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	partition aux_classe_produtos = m
		mode: import
		queryGroup: auxiliares
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("VY9NCsIwEIWvMmRdwfrvWgRX4r50EZMRB0xSJvVELsQDeIJczElqQbfve+8bpmnUTrsO0xujqlSt2qpRJw723ocIF0ovyvlsyEOP3pCmHzL/XzAa9H1xLUbiKMbAJVt+MzQUtQOLoEWZnukRhK5GGsUAGq50RvaaBa0L2jtgiiZ3NyU4yhC6IH7okC3y5BbynW2hh2HvbR7U08EuNbKlVMu37Qc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Segmentação = _t, Id = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Source,{{"Segmentação", type text}, {"Id", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

